#!/bin/sh -x

# create database with name as capstone_fsnd_test
DATABASE_NAME='capstone_fsnd_test'
if psql -lqt | cut -d \| -f 1 | grep -qw $DATABASE_NAME; then
    echo "A database with the name $DBNAME already exists."
    echo "Drop $DATABASE_NAME and create a new one."
    dropdb $DATABASE_NAME
fi
createdb $DATABASE_NAME
psql 'capstone_fsnd_test'< 'capstone_fsnd_test.psql'

# Export the environment variables and set up for the server
export DATABASE_URL='postgresql://localhost:5432/capstone_fsnd_test' 
export SUPREME_LEADER_TOKEN='eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6InJyQmlLREd2NEJScWNxdkZMY2tnLSJ9.eyJpc3MiOiJodHRwczovL2Nvd2ZmZWVzaG9wLnVzLmF1dGgwLmNvbS8iLCJzdWIiOiJhdXRoMHw1Zjk4MGMyODczMDVhMjAwNzY5MGZiODMiLCJhdWQiOiJjYXBzdG9uZS1hcGkiLCJpYXQiOjE2MDM4ODI2OTMsImV4cCI6MTYwMzk2OTA5MywiYXpwIjoiOXRoT2JEWWlseGt4alk4Y1d2eW5UaUY0aGpINXZ5eEQiLCJzY29wZSI6IiIsInBlcm1pc3Npb25zIjpbImRlbGV0ZTpiYXNlIiwiZGVsZXRlOmNyZXciLCJnZXQ6YmFzZSIsImdldDpjcmV3IiwicGF0Y2g6YmFzZSIsInBhdGNoOmNyZXciLCJwb3N0OmJhc2UiLCJwb3N0OmNyZXciXX0.aNHDqIVq0kdvngFZML5xDxOXi15LnwVuIfl5NEJcB_cjM2d1fr-I6h_ymOAx4tUd_nVhj3WpY1wcGZz5nB1BFbsozmKQXK8x1mrpGYdx-cuIhipEPYqhsyR_hQemvUX1xCBVt39LvidoCFKbZ30fP1mGjbXjK3O1iZEarnKMtc98e2IFUEGBoWPSwHF1KkFKRxfqDM52kibfzk6XKRgVDnUNn7pP4q4fh3t_O7vUmneirtoK-SkfykgTJR1s1XKozSlWSTn6TZmBceIrJTaDUTZ_9sOJnxAKMDd5Y1MKmWN78TuIDgTf17BdKBfVT5uvqkl7siV2HEDLUTbVWG71WA'
export CREW_TOKEN='eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6InJyQmlLREd2NEJScWNxdkZMY2tnLSJ9.eyJpc3MiOiJodHRwczovL2Nvd2ZmZWVzaG9wLnVzLmF1dGgwLmNvbS8iLCJzdWIiOiJhdXRoMHw1Zjk4MTMwMmVkYzY0YTAwNjgyMDAyNGUiLCJhdWQiOiJjYXBzdG9uZS1hcGkiLCJpYXQiOjE2MDM4ODI1OTYsImV4cCI6MTYwMzk2ODk5NiwiYXpwIjoiOXRoT2JEWWlseGt4alk4Y1d2eW5UaUY0aGpINXZ5eEQiLCJzY29wZSI6IiIsInBlcm1pc3Npb25zIjpbImdldDpiYXNlIiwiZ2V0OmNyZXciXX0.HHIH8s8dYoBXFYbMHYGzrZVbCCpKmY4p6NRDgHEFN9LOqRVZKEoBRR0jNx0-gbkzZPbYUGcSlgvQwdJiBmva1CEOTYREQZtD7apwrZaHLDXv2F-0DK_m38sHnGnKv6KAb1asyhvhoIFa6WpXazVBfas3BIH3DPLdmeJn6XbkZwwkery-3yrRq2obAIsCOvqj4qLJ-at6qqJjAnrszTKH9slN54QzgV_cpDviY5V0L0G99-fOYVJ2-tqX8S0wbHwtTcV7yNvO2o5ljWfeYM7DPpkfsoVeMJ3jalvvZIr4l7xNOjzhp0evJVvG14X8x0ox9UTwvX-hibZI9fghWKeKog'
python3 -m test.py -v