"""empty message

Revision ID: a1d8ab19bea5
Revises: 
Create Date: 2020-10-27 23:01:00.641820

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1d8ab19bea5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('base',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('planet', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('crew',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('rank', sa.String(), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('bio', sa.String(), nullable=True),
    sa.Column('base_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['base_id'], ['base.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('crew')
    op.drop_table('base')
    # ### end Alembic commands ###
